<?php

namespace Database\Seeders;
use App\Models\PenjadwalanKapal;
use App\Models\PenjadwalanModel;
use App\Models\Schedule;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PenjadwalanKapalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jadwals = [
            [
                'id_kapal' => 1,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 2,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 3,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 4,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 5,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 6,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 7,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 8,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 9,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 10,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 11,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-08-09',
                'tiba_dari' => 'awokawok',
                'posisi_tambat' => 'wkkwkw',
                'tujuan' => 'KKN',
                'tanggal_rencana_berangkat' => '2023-09-28',
            ],
            [
                'id_kapal' => 12,
                'nama_kapal' => 'MT. Sky Blue',
                'tanggal_tiba' => '2023-08-10',
                'tiba_dari' => 'sipp',
                'posisi_tambat' => 'pinggiran jalan',
                'tujuan' => 'KKN Tematik',
                'tanggal_rencana_berangkat' => '2023-10-28',
            ],
            [
                'id_kapal' => 13,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-07-08',
                'tiba_dari' => 'Malahayati',
                'posisi_tambat' => 'D.Hagu',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-09',
            ],
            [
                'id_kapal' => 14,
                'nama_kapal' => 'MT. Brilliant 8899',
                'tanggal_tiba' => '2023-06-28',
                'tiba_dari' => 'Tlk.Bayur',
                'posisi_tambat' => 'D.umum',
                'tujuan' => 'Tlk.Bayur',
                'tanggal_rencana_berangkat' => '2023-07-10',
            ],
            [
                'id_kapal' => 15,
                'nama_kapal' => 'KM. Berau Mas',
                'tanggal_tiba' => '2023-07-09',
                'tiba_dari' => 'Klang',
                'posisi_tambat' => 'D.umum',
                'tujuan' => 'Kushiro',
                'tanggal_rencana_berangkat' => '2023-07-11',
            ],
            [
                'id_kapal' => 16,
                'nama_kapal' => 'MV. Sawah Lunto',
                'tanggal_tiba' => '2023-07-11',
                'tiba_dari' => 'Klang',
                'posisi_tambat' => 'D.umum',
                'tujuan' => 'Kushiro',
                'tanggal_rencana_berangkat' => '2023-07-12',
            ],
            [
                'id_kapal' => 17,
                'nama_kapal' => 'MT. Aerosea Catalina',
                'tanggal_tiba' => '2023-07-11',
                'tiba_dari' => 'Lhoknga',
                'posisi_tambat' => 'D.umum',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-12',
            ],
            [
                'id_kapal' => 18,
                'nama_kapal' => 'MV. Oceanic Success',
                'tanggal_tiba' => '2023-07-13',
                'tiba_dari' => 'K. Tanjung',
                'posisi_tambat' => 'D.umum',
                'tujuan' => 'Malahayati',
                'tanggal_rencana_berangkat' => '2023-07-13',
            ],
            [
                'id_kapal' => 19,
                'nama_kapal' => 'MT. Triaksa 17',
                'tanggal_tiba' => '2023-07-13',
                'tiba_dari' => 'Tg.Uban',
                'posisi_tambat' => 'D.Hagu',
                'tujuan' => 'Malahayati',
                'tanggal_rencana_berangkat' => '2023-07-14',
            ],
            [
                'id_kapal' => 20,
                'nama_kapal' => 'KM. Illannur',
                'tanggal_tiba' => '2023-07-13',
                'tiba_dari' => 'Lhoknga',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-14',
            ],
            [
                'id_kapal' => 21,
                'nama_kapal' => 'MV. Glorious Jupiter',
                'tanggal_tiba' => '2023-07-03',
                'tiba_dari' => 'Tlk.Bayur',
                'posisi_tambat' => 'D.Asean',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-15',
            ],
            [
                'id_kapal' => 22,
                'nama_kapal' => 'MT. triaksa 17',
                'tanggal_tiba' => '2023-07-14',
                'tiba_dari' => 'Belawan',
                'posisi_tambat' => 'D.Hagu',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-15',
            ],
            [
                'id_kapal' => 23,
                'nama_kapal' => 'KM. Ilannur',
                'tanggal_tiba' => '2023-07-16',
                'tiba_dari' => 'Tg. Uban',
                'posisi_tambat' => 'D.Hagu',
                'tujuan' => 'Malahayati',
                'tanggal_rencana_berangkat' => '2023-07-16',
            ],
            [
                'id_kapal' => 24,
                'nama_kapal' => 'MV.Glorious Jupiter',
                'tanggal_tiba' => '2023-07-05',
                'tiba_dari' => 'Tlk. Bayur',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Tlk. Bayur',
                'tanggal_rencana_berangkat' => '2023-07-17',
            ],
            [
                'id_kapal' => 25,
                'nama_kapal' => 'MT. Garuda Asia',
                'tanggal_tiba' => '2023-07-07',
                'tiba_dari' => 'Sai Gon New Port',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Singapore',
                'tanggal_rencana_berangkat' => '2023-07-18',
            ],
            [
                'id_kapal' => 26,
                'nama_kapal' =>  'MT. Nacc Cozumel',
                'tanggal_tiba' => '2023-07-17',
                'tiba_dari' => 'Lhoknga',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-18',
            ],
            [
                'id_kapal' => 27,
                'nama_kapal' =>   'KM. Berau Mas',
                'tanggal_tiba' => '2023-07-18',
                'tiba_dari' => 'Belawan',
                'posisi_tambat' => 'D.Hagu',
                'tujuan' => 'Sanga-sanga',
                'tanggal_rencana_berangkat' => '2023-07-20',
            ],
            [
                'id_kapal' => 28,
                'nama_kapal' => 'MT. Brilliant 8899',
                'tanggal_tiba' => '2023-07-19',
                'tiba_dari' => 'Loknga',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-20',
            ],
            [
                'id_kapal' => 29,
                'nama_kapal' => 'MV. Oceanic success',
                'tanggal_tiba' => '2023-07-22',
                'tiba_dari' => 'Loknga',
                'posisi_tambat' => 'D.Umum',
                'tujuan' => 'Belawan',
                'tanggal_rencana_berangkat' => '2023-07-23',
            ],
        ];

        foreach ($jadwals as $jadwal){
            Schedule::create($jadwal);
        }
    }
}
